# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 669)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(599, 0, 331, 401))
        self.frame_3.setStyleSheet("background-color: rgb(57, 57, 57);\n"
"QLabel{\n"
"    font-size:14px;\n"
"    color:white;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lbl_foto = QtWidgets.QLabel(self.frame_3)
        self.lbl_foto.setGeometry(QtCore.QRect(13, 10, 310, 220))
        self.lbl_foto.setStyleSheet("background-color: rgb(109, 109, 162);\n"
"")
        self.lbl_foto.setText("")
        self.lbl_foto.setObjectName("lbl_foto")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 240, 311, 151))
        self.groupBox_2.setStyleSheet("color:white;\n"
"font-size:16px;\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(-1, 0, -1, -1)
        self.formLayout.setHorizontalSpacing(30)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lbl_yas = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_yas.setObjectName("lbl_yas")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_yas)
        self.lbl_duygu = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_duygu.setObjectName("lbl_duygu")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_duygu)
        self.lbl_cinsiyet = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_cinsiyet.setObjectName("lbl_cinsiyet")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_cinsiyet)
        self.lbl_irk = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_irk.setObjectName("lbl_irk")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_irk)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(600, 400, 331, 220))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"font-size:24px;\n"
"border:none;\n"
"background-color: rgb(63, 63, 63);\n"
"color:white;\n"
"}\n"
"QCheckBox{\n"
"color:white;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.yas_check = QtWidgets.QCheckBox(self.groupBox)
        self.yas_check.setGeometry(QtCore.QRect(20, 40, 141, 31))
        self.yas_check.setChecked(True)
        self.yas_check.setObjectName("yas_check")
        self.duygu_check = QtWidgets.QCheckBox(self.groupBox)
        self.duygu_check.setGeometry(QtCore.QRect(20, 70, 181, 31))
        self.duygu_check.setChecked(True)
        self.duygu_check.setObjectName("duygu_check")
        self.cins_check = QtWidgets.QCheckBox(self.groupBox)
        self.cins_check.setGeometry(QtCore.QRect(20, 100, 181, 31))
        self.cins_check.setChecked(True)
        self.cins_check.setObjectName("cins_check")
        self.btn_ayar = QtWidgets.QPushButton(self.groupBox)
        self.btn_ayar.setGeometry(QtCore.QRect(170, 30, 141, 41))
        self.btn_ayar.setObjectName("btn_ayar")
        self.btn_startAnalysis = QtWidgets.QPushButton(self.groupBox)
        self.btn_startAnalysis.setGeometry(QtCore.QRect(10, 170, 301, 41))
        self.btn_startAnalysis.setObjectName("btn_startAnalysis")
        self.irk_check = QtWidgets.QCheckBox(self.groupBox)
        self.irk_check.setGeometry(QtCore.QRect(20, 130, 131, 31))
        self.irk_check.setChecked(True)
        self.irk_check.setObjectName("irk_check")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 600, 621))
        self.frame_2.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 26))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtWidgets.QMenu(self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        self.menuEkle = QtWidgets.QMenu(self.menubar)
        self.menuEkle.setObjectName("menuEkle")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionResim_Ekle = QtWidgets.QAction(MainWindow)
        self.actionResim_Ekle.setObjectName("actionResim_Ekle")
        self.actionStart_Cam = QtWidgets.QAction(MainWindow)
        self.actionStart_Cam.setObjectName("actionStart_Cam")
        self.actionStop_Cam = QtWidgets.QAction(MainWindow)
        self.actionStop_Cam.setObjectName("actionStop_Cam")
        self.menuDosya.addAction(self.actionStart_Cam)
        self.menuDosya.addAction(self.actionStop_Cam)
        self.menuEkle.addAction(self.actionResim_Ekle)
        self.menuExit.addAction(self.actionExit)
        self.menubar.addAction(self.menuDosya.menuAction())
        self.menubar.addAction(self.menuEkle.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Yaş :"))
        self.label_3.setText(_translate("MainWindow", "Duygu :"))
        self.label_4.setText(_translate("MainWindow", "Cinsiyet :"))
        self.label_5.setText(_translate("MainWindow", "Irk :"))
        self.lbl_yas.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_duygu.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_cinsiyet.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_irk.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox.setTitle(_translate("MainWindow", "Yüz Analiz"))
        self.yas_check.setText(_translate("MainWindow", "Yaş Analizi"))
        self.duygu_check.setText(_translate("MainWindow", "Duygu Analizi"))
        self.cins_check.setText(_translate("MainWindow", "Cinsiyet Analizi"))
        self.btn_ayar.setText(_translate("MainWindow", "Resim Analizi Yap"))
        self.btn_startAnalysis.setText(_translate("MainWindow", "Kameradan Analiz Yap"))
        self.irk_check.setText(_translate("MainWindow", "Irk Analizi"))
        self.menuDosya.setTitle(_translate("MainWindow", "Dosya"))
        self.menuEkle.setTitle(_translate("MainWindow", "Ekle"))
        self.menuExit.setTitle(_translate("MainWindow", "Exit"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionResim_Ekle.setText(_translate("MainWindow", "Resim Ekle"))
        self.actionStart_Cam.setText(_translate("MainWindow", "Start Cam"))
        self.actionStop_Cam.setText(_translate("MainWindow", "Stop Cam"))
import resources_rc
